// Package surveillance_uss_v0 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package surveillance_uss_v0

import (
	"fmt"
	"net/http"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// /uss/aircraft
	// (GET /uss/flights/stream)
	StreamFlights(ctx echo.Context, params StreamFlightsParams) error
	// /uss/traffic_surveilled_areas/{id}
	// (GET /uss/traffic_surveilled_areas/{id})
	GetTrafficSurveilledAreaDetails(ctx echo.Context, id EntityUUID) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// StreamFlights converts echo context to params.
func (w *ServerInterfaceWrapper) StreamFlights(ctx echo.Context) error {
	var err error

	ctx.Set(AuthorityScopes, []string{"surveillance.display_provider"})

	// Parameter object where we will unmarshal all parameters from the context
	var params StreamFlightsParams
	// ------------- Required query parameter "view" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "view", ctx.QueryParams(), &params.View, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter view: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.StreamFlights(ctx, params)
	return err
}

// GetTrafficSurveilledAreaDetails converts echo context to params.
func (w *ServerInterfaceWrapper) GetTrafficSurveilledAreaDetails(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id EntityUUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(AuthorityScopes, []string{"surveillance.display_provider"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTrafficSurveilledAreaDetails(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/uss/flights/stream", wrapper.StreamFlights)
	router.GET(baseURL+"/uss/traffic_surveilled_areas/:id", wrapper.GetTrafficSurveilledAreaDetails)

}
