// Package surveillance_uss_v0 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package surveillance_uss_v0

import (
	"time"
)

const (
	AuthorityScopes = "Authority.Scopes"
)

// Defines values for AircraftType.
const (
	Aeroplane               AircraftType = "Aeroplane"
	Airship                 AircraftType = "Airship"
	CaptiveBalloon          AircraftType = "CaptiveBalloon"
	FreeBalloon             AircraftType = "FreeBalloon"
	FreeFallOrParachute     AircraftType = "FreeFallOrParachute"
	Glider                  AircraftType = "Glider"
	GroundObstacle          AircraftType = "GroundObstacle"
	Gyroplane               AircraftType = "Gyroplane"
	Helicopter              AircraftType = "Helicopter"
	HybridLift              AircraftType = "HybridLift"
	Kite                    AircraftType = "Kite"
	NotDeclared             AircraftType = "NotDeclared"
	Ornithopter             AircraftType = "Ornithopter"
	Other                   AircraftType = "Other"
	Rocket                  AircraftType = "Rocket"
	TetheredPoweredAircraft AircraftType = "TetheredPoweredAircraft"
)

// Valid indicates whether the value is a known member of the AircraftType enum.
func (e AircraftType) Valid() bool {
	switch e {
	case Aeroplane:
		return true
	case Airship:
		return true
	case CaptiveBalloon:
		return true
	case FreeBalloon:
		return true
	case FreeFallOrParachute:
		return true
	case Glider:
		return true
	case GroundObstacle:
		return true
	case Gyroplane:
		return true
	case Helicopter:
		return true
	case HybridLift:
		return true
	case Kite:
		return true
	case NotDeclared:
		return true
	case Ornithopter:
		return true
	case Other:
		return true
	case Rocket:
		return true
	case TetheredPoweredAircraft:
		return true
	default:
		return false
	}
}

// Defines values for AltitudeReference.
const (
	W84 AltitudeReference = "W84"
)

// Valid indicates whether the value is a known member of the AltitudeReference enum.
func (e AltitudeReference) Valid() bool {
	switch e {
	case W84:
		return true
	default:
		return false
	}
}

// Defines values for AltitudeUnits.
const (
	AltitudeUnitsM AltitudeUnits = "M"
)

// Valid indicates whether the value is a known member of the AltitudeUnits enum.
func (e AltitudeUnits) Valid() bool {
	switch e {
	case AltitudeUnitsM:
		return true
	default:
		return false
	}
}

// Defines values for RadiusUnits.
const (
	RadiusUnitsM RadiusUnits = "M"
)

// Valid indicates whether the value is a known member of the RadiusUnits enum.
func (e RadiusUnits) Valid() bool {
	switch e {
	case RadiusUnitsM:
		return true
	default:
		return false
	}
}

// Defines values for TimeFormat.
const (
	RFC3339 TimeFormat = "RFC3339"
)

// Valid indicates whether the value is a known member of the TimeFormat enum.
func (e TimeFormat) Valid() bool {
	switch e {
	case RFC3339:
		return true
	default:
		return false
	}
}

// AircraftId Identification of the aircraft. At least one field of this object must be specified.
type AircraftId struct {
	// Icao The ICAO hex code broadcast by the transponder. This is a six-digit hexadecimal [0-9,a-f] code.
	Icao *string `json:"icao,omitempty"`

	// IcaoType The standard aircraft type code as published by the ICAO. For example, a Cessna 172 is “C172” and a Boeing 777-300 is “B773”
	IcaoType *string `json:"icao_type,omitempty"`

	// Registration Aircraft Registration or “Tail Number”. These should be entered in all caps.
	Registration *string `json:"registration,omitempty"`
}

// AircraftPosition Position of an aircraft.
type AircraftPosition struct {
	// Alt Geodetic altitude (NOT altitude above launch, altitude above ground, or EGM96): aircraft distance above the WGS84 ellipsoid as measured along a line that passes through the aircraft and is normal to the surface of the WGS84 ellipsoid.  This value is provided in meters and must have a minimum resolution of 1 meter.  Invalid, No Value or Unknown is -1000 m.
	Alt *float32 `json:"alt,omitempty"`

	// Lat Degrees of latitude north of the equator, with reference to the WGS84 ellipsoid.  Invalid, No Value, or Unknown is 0 degrees (both Lat/Lon).
	Lat *Latitude `json:"lat,omitempty"`

	// Lng Degrees of longitude east of the Prime Meridian, with reference to the WGS84 ellipsoid.  Invalid, No Value, or Unknown is 0 degrees (both Lat/Lon).
	Lng *Longitude `json:"lng,omitempty"`

	// PressureAltitude The uncorrected altitude (based on reference standard 29.92 inHg, 1013.25 mb) provides a reference for algorithms that utilize "altitude deltas" between aircraft.  This value is provided in meters and must have a minimum resolution of 1 meter.  Invalid, No Value or Unknown is -1000 m.
	PressureAltitude *float32 `json:"pressure_altitude,omitempty"`
}

// AircraftState defines model for AircraftState.
type AircraftState struct {
	// Position Position of an aircraft.
	Position AircraftPosition `json:"position"`

	// Speed Ground speed of flight in meters per second.  Invalid, No Value, or Unknown is 255 m/s, if speed is >254.25 m/s then report 254.25 m/s.
	Speed     *float32 `json:"speed,omitempty"`
	Timestamp Time     `json:"timestamp"`

	// Track Direction of flight expressed as a "True North-based" ground track angle.  This value is provided in clockwise degrees with a minimum resolution of 1 degree.  If aircraft is not moving horizontally, use the "Unknown" value.  A value of 361 indicates invalid, no value, or unknown.
	Track *float32 `json:"track,omitempty"`

	// VerticalSpeed Speed up (vertically) WGS84-HAE, m/s.  Invalid, No Value, or Unknown is 63 m/s, if speed is >62 m/s then report 62 m/s.
	VerticalSpeed *float32 `json:"vertical_speed,omitempty"`
}

// AircraftType defines model for AircraftType.
type AircraftType string

// Altitude defines model for Altitude.
type Altitude struct {
	// Reference A code indicating the reference for a vertical distance. See AIXM 5.1 and FIXM 4.2.0. Currently, UTM only allows WGS84 with no immediate plans to allow other options. FIXM and AIXM allow for 'SFC' which is equivalent to AGL.
	Reference AltitudeReference `json:"reference"`

	// Units The reference quantities used to express the value of altitude. See FIXM 4.2. Currently, UTM only allows meters with no immediate plans to allow other options.
	Units AltitudeUnits `json:"units"`

	// Value The numeric value of the altitude. Note that min and max values are added as a sanity check. As use cases evolve and more options are made available in terms of units of measure or reference systems, these bounds may be re-evaluated. Invalid, No Value, or Unknown is –1000 m.
	Value float64 `json:"value"`
}

// AltitudeReference A code indicating the reference for a vertical distance. See AIXM 5.1 and FIXM 4.2.0. Currently, UTM only allows WGS84 with no immediate plans to allow other options. FIXM and AIXM allow for 'SFC' which is equivalent to AGL.
type AltitudeReference string

// AltitudeUnits The reference quantities used to express the value of altitude. See FIXM 4.2. Currently, UTM only allows meters with no immediate plans to allow other options.
type AltitudeUnits string

// Circle A circular area on the surface of the earth.
type Circle struct {
	// Center Point on the earth's surface.
	Center *LatLngPoint `json:"center,omitempty"`
	Radius *Radius      `json:"radius,omitempty"`
}

// DataSource defines model for DataSource.
type DataSource struct {
	// Data Raw data
	Data string `json:"data"`

	// Format Data source data format
	Format string `json:"format"`

	// Id Data source identifier
	Id string `json:"id"`
}

// EntityUUID UUID v4.
type EntityUUID = UUIDv4

// ErrorResponse Human-readable string returned when an error occurs as a result of a USS - DSS transaction.
type ErrorResponse struct {
	// Message Human-readable message indicating what error occurred and/or why.
	Message *string `json:"message,omitempty"`
}

// Flight Description of flight.
type Flight struct {
	// AircraftId Identification of the aircraft. At least one field of this object must be specified.
	AircraftId   AircraftId    `json:"aircraft_id"`
	AircraftType AircraftType  `json:"aircraft_type"`
	CurrentState AircraftState `json:"current_state"`
	Source       DataSource    `json:"source"`
}

// FlightEvent defines model for FlightEvent.
type FlightEvent struct {
	// Data Description of flight.
	Data Flight `json:"data"`
}

// GetTrafficSurveilledAreaDetailsResponse Response to request for the details of an surveilled area with the given ID.
type GetTrafficSurveilledAreaDetailsResponse struct {
	// Extents Contiguous block of geographic spacetime.
	Extents Volume4D `json:"extents"`
}

// LatLngPoint Point on the earth's surface.
type LatLngPoint struct {
	// Lat Degrees of latitude north of the equator, with reference to the WGS84 ellipsoid.  Invalid, No Value, or Unknown is 0 degrees (both Lat/Lon).
	Lat Latitude `json:"lat"`

	// Lng Degrees of longitude east of the Prime Meridian, with reference to the WGS84 ellipsoid.  Invalid, No Value, or Unknown is 0 degrees (both Lat/Lon).
	Lng Longitude `json:"lng"`
}

// Latitude Degrees of latitude north of the equator, with reference to the WGS84 ellipsoid.  Invalid, No Value, or Unknown is 0 degrees (both Lat/Lon).
type Latitude = float64

// Longitude Degrees of longitude east of the Prime Meridian, with reference to the WGS84 ellipsoid.  Invalid, No Value, or Unknown is 0 degrees (both Lat/Lon).
type Longitude = float64

// Polygon An enclosed area on the earth. The bounding edges of this polygon are defined to be the shortest paths between connected vertices.  This means, for instance, that the edge between two points both defined at a particular latitude is not generally contained at that latitude. The winding order must be interpreted as the order which produces the smaller area. The path between two vertices is defined to be the shortest possible path between those vertices. Edges may not cross. Vertices may not be duplicated.  In particular, the final polygon vertex must not be identical to the first vertex.
type Polygon struct {
	Vertices []LatLngPoint `json:"vertices"`
}

// Radius defines model for Radius.
type Radius struct {
	// Units FIXM-compatible units.  Only meters ("M") are acceptable for UTM.
	Units RadiusUnits `json:"units"`

	// Value Distance from the centerpoint of a circular area, along the WGS84 ellipsoid.
	Value float32 `json:"value"`
}

// RadiusUnits FIXM-compatible units.  Only meters ("M") are acceptable for UTM.
type RadiusUnits string

// SubscriptionUUID UUID v4.
type SubscriptionUUID = UUIDv4

// Time defines model for Time.
type Time struct {
	Format TimeFormat `json:"format"`

	// Value RFC3339-formatted time/date string.  The time zone must be 'Z'.
	Value time.Time `json:"value"`
}

// TimeFormat defines model for Time.Format.
type TimeFormat string

// UUIDv4 UUID v4.
type UUIDv4 = string

// View The area of this view: lat1,lng1,lat2,lng2. The view is the smallest box bounded by the provided corner points.
type View = string

// Volume3D A three-dimensional geographic volume consisting of a vertically-extruded shape. Exactly one outline must be specified.
type Volume3D struct {
	AltitudeLower *Altitude `json:"altitude_lower,omitempty"`
	AltitudeUpper *Altitude `json:"altitude_upper,omitempty"`

	// OutlineCircle A circular area on the surface of the earth.
	OutlineCircle *Circle `json:"outline_circle,omitempty"`

	// OutlinePolygon An enclosed area on the earth. The bounding edges of this polygon are defined to be the shortest paths between connected vertices.  This means, for instance, that the edge between two points both defined at a particular latitude is not generally contained at that latitude. The winding order must be interpreted as the order which produces the smaller area. The path between two vertices is defined to be the shortest possible path between those vertices. Edges may not cross. Vertices may not be duplicated.  In particular, the final polygon vertex must not be identical to the first vertex.
	OutlinePolygon *Polygon `json:"outline_polygon,omitempty"`
}

// Volume4D Contiguous block of geographic spacetime.
type Volume4D struct {
	TimeEnd   *Time `json:"time_end,omitempty"`
	TimeStart *Time `json:"time_start,omitempty"`

	// Volume A three-dimensional geographic volume consisting of a vertically-extruded shape. Exactly one outline must be specified.
	Volume Volume3D `json:"volume"`
}

// StreamFlightsParams defines parameters for StreamFlights.
type StreamFlightsParams struct {
	// View The area of this view: lat1,lng1,lat2,lng2. The view is the smallest box bounded by the provided corner points.
	View View `form:"view" json:"view"`
}
