// Package surveillance_dss_v0 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package surveillance_dss_v0

import (
	"fmt"
	"net/http"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// /dss/subscriptions
	// (GET /dss/subscriptions)
	SearchSubscriptions(ctx echo.Context, params SearchSubscriptionsParams) error
	// /dss/subscriptions/{id}
	// (GET /dss/subscriptions/{id})
	GetSubscription(ctx echo.Context, id SubscriptionUUID) error
	// /dss/subscriptions/{id}
	// (PUT /dss/subscriptions/{id})
	CreateSubscription(ctx echo.Context, id SubscriptionUUID) error
	// /dss/subscriptions/{id}/{version}
	// (DELETE /dss/subscriptions/{id}/{version})
	DeleteSubscription(ctx echo.Context, id SubscriptionUUID, version string) error
	// /dss/subscriptions/{id}/{version}
	// (PUT /dss/subscriptions/{id}/{version})
	UpdateSubscription(ctx echo.Context, id SubscriptionUUID, version string) error
	// /dss/traffic_surveilled_areas
	// (GET /dss/traffic_surveilled_areas)
	SearchTrafficSurveilledAreas(ctx echo.Context, params SearchTrafficSurveilledAreasParams) error
	// /dss/traffic_surveilled_areas/{id}
	// (GET /dss/traffic_surveilled_areas/{id})
	GetTrafficSurveilledArea(ctx echo.Context, id EntityUUID) error
	// /dss/traffic_surveilled_areas/{id}
	// (PUT /dss/traffic_surveilled_areas/{id})
	CreateTrafficSurveilledArea(ctx echo.Context, id EntityUUID) error
	// /dss/traffic_surveilled_areas/{id}/{version}
	// (DELETE /dss/traffic_surveilled_areas/{id}/{version})
	DeleteTrafficSurveilledArea(ctx echo.Context, id EntityUUID, version string) error
	// /dss/traffic_surveilled_areas/{id}/{version}
	// (PUT /dss/traffic_surveilled_areas/{id}/{version})
	UpdateTrafficSurveilledArea(ctx echo.Context, id EntityUUID, version string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// SearchSubscriptions converts echo context to params.
func (w *ServerInterfaceWrapper) SearchSubscriptions(ctx echo.Context) error {
	var err error

	ctx.Set(AuthorityScopes, []string{"surveillance.display_provider"})

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchSubscriptionsParams
	// ------------- Required query parameter "area" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "area", ctx.QueryParams(), &params.Area, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter area: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SearchSubscriptions(ctx, params)
	return err
}

// GetSubscription converts echo context to params.
func (w *ServerInterfaceWrapper) GetSubscription(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id SubscriptionUUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(AuthorityScopes, []string{"surveillance.display_provider"})

	ctx.Set(AuthorityScopes, []string{"surveillance.service_provider"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetSubscription(ctx, id)
	return err
}

// CreateSubscription converts echo context to params.
func (w *ServerInterfaceWrapper) CreateSubscription(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id SubscriptionUUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(AuthorityScopes, []string{"surveillance.display_provider"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateSubscription(ctx, id)
	return err
}

// DeleteSubscription converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteSubscription(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id SubscriptionUUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// ------------- Path parameter "version" -------------
	var version string

	err = runtime.BindStyledParameterWithOptions("simple", "version", ctx.Param("version"), &version, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter version: %s", err))
	}

	ctx.Set(AuthorityScopes, []string{"surveillance.display_provider"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteSubscription(ctx, id, version)
	return err
}

// UpdateSubscription converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateSubscription(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id SubscriptionUUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// ------------- Path parameter "version" -------------
	var version string

	err = runtime.BindStyledParameterWithOptions("simple", "version", ctx.Param("version"), &version, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter version: %s", err))
	}

	ctx.Set(AuthorityScopes, []string{"surveillance.display_provider"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateSubscription(ctx, id, version)
	return err
}

// SearchTrafficSurveilledAreas converts echo context to params.
func (w *ServerInterfaceWrapper) SearchTrafficSurveilledAreas(ctx echo.Context) error {
	var err error

	ctx.Set(AuthorityScopes, []string{"surveillance.display_provider"})

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchTrafficSurveilledAreasParams
	// ------------- Required query parameter "area" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "area", ctx.QueryParams(), &params.Area, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter area: %s", err))
	}

	// ------------- Required query parameter "earliest_time" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "earliest_time", ctx.QueryParams(), &params.EarliestTime, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter earliest_time: %s", err))
	}

	// ------------- Required query parameter "latest_time" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "latest_time", ctx.QueryParams(), &params.LatestTime, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter latest_time: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SearchTrafficSurveilledAreas(ctx, params)
	return err
}

// GetTrafficSurveilledArea converts echo context to params.
func (w *ServerInterfaceWrapper) GetTrafficSurveilledArea(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id EntityUUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(AuthorityScopes, []string{"surveillance.display_provider"})

	ctx.Set(AuthorityScopes, []string{"surveillance.service_provider"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTrafficSurveilledArea(ctx, id)
	return err
}

// CreateTrafficSurveilledArea converts echo context to params.
func (w *ServerInterfaceWrapper) CreateTrafficSurveilledArea(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id EntityUUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(AuthorityScopes, []string{"surveillance.service_provider"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateTrafficSurveilledArea(ctx, id)
	return err
}

// DeleteTrafficSurveilledArea converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteTrafficSurveilledArea(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id EntityUUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// ------------- Path parameter "version" -------------
	var version string

	err = runtime.BindStyledParameterWithOptions("simple", "version", ctx.Param("version"), &version, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter version: %s", err))
	}

	ctx.Set(AuthorityScopes, []string{"surveillance.service_provider"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteTrafficSurveilledArea(ctx, id, version)
	return err
}

// UpdateTrafficSurveilledArea converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateTrafficSurveilledArea(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id EntityUUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// ------------- Path parameter "version" -------------
	var version string

	err = runtime.BindStyledParameterWithOptions("simple", "version", ctx.Param("version"), &version, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter version: %s", err))
	}

	ctx.Set(AuthorityScopes, []string{"surveillance.service_provider"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateTrafficSurveilledArea(ctx, id, version)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/dss/subscriptions", wrapper.SearchSubscriptions)
	router.GET(baseURL+"/dss/subscriptions/:id", wrapper.GetSubscription)
	router.PUT(baseURL+"/dss/subscriptions/:id", wrapper.CreateSubscription)
	router.DELETE(baseURL+"/dss/subscriptions/:id/:version", wrapper.DeleteSubscription)
	router.PUT(baseURL+"/dss/subscriptions/:id/:version", wrapper.UpdateSubscription)
	router.GET(baseURL+"/dss/traffic_surveilled_areas", wrapper.SearchTrafficSurveilledAreas)
	router.GET(baseURL+"/dss/traffic_surveilled_areas/:id", wrapper.GetTrafficSurveilledArea)
	router.PUT(baseURL+"/dss/traffic_surveilled_areas/:id", wrapper.CreateTrafficSurveilledArea)
	router.DELETE(baseURL+"/dss/traffic_surveilled_areas/:id/:version", wrapper.DeleteTrafficSurveilledArea)
	router.PUT(baseURL+"/dss/traffic_surveilled_areas/:id/:version", wrapper.UpdateTrafficSurveilledArea)

}
